project_id = "buildstart-selfhosted"

[functions.webhook-wsender-kasuni_science]
verify_jwt = false
[functions.process-message-kasuni_science]
verify_jwt = false
[functions.assetlinks-kasuni_science]
verify_jwt = false
